### ISSUE TITLE
Error while Updating Pricing Rule

### ISSUE THREAD

**Issue by soloincc** [bcornwellmott/velometro#22]
I have tried to implement this patch but I am getting an error when the `from_supplier_quotation` field is being updated. See the trace below. I have checked in the Pricing Rule table and I don't have such a field. Which ERPNext version are you using?

> 
Traceback (most recent call last):
  File "/www/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/www/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/www/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/www/frappe-bench/apps/frappe/frappe/__init__.py", line 884, in call
    return fn(*args, **newargs)
  File "/www/frappe-bench/apps/velometro/velometro/velometro/supplier_quotation.py", line 54, in add_pricing_rules
    frappe.set_value("Pricing Rule", pricing_rule.name, "from_supplier_quotation",quotation.name)
  File "/www/frappe-bench/apps/frappe/frappe/__init__.py", line 564, in set_value
    return frappe.client.set_value(doctype, docname, fieldname, value)
  File "/www/frappe-bench/apps/frappe/frappe/client.py", line 66, in set_value
    if df.fieldtype == "Read Only" or df.read_only:
AttributeError: 'NoneType' object has no attribute 'fieldtype'

**Comment by bcornwellmott** [comment]
Sorry... it is a custom field:

![image](https://cloud.githubusercontent.com/assets/16806041/18918685/7a3ad09e-8550-11e6-84e7-4ef535e059b6.png)

I suggest you manually add it for now. I've had issues trying to import custom fields through an app so I'm avoiding doing it here until I can sort that out.

**Comment by bcornwellmott** [comment]
Fixed in Pull #26
